#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/../lib/sdwpf_log.sh"

# Leakage-safe full method: fold-matched PromptTimeDART pretraining followed by
# supervised fine-tuning.  Test evaluation is intentionally a separate command.
SEED="${SEED:-2024}"
FOLD="${FOLD:-0}"
N_FOLDS="${N_FOLDS:-3}"
SPLIT="${SPLIT:-rolling_holdout}"
PRED_LEN="${PRED_LEN:-12}"
PRETRAIN_PRED_LEN="${PRETRAIN_PRED_LEN:-24}"
PRETRAIN_EPOCHS="${PRETRAIN_EPOCHS:-20}"
PRETRAIN_LEARNING_RATE="${PRETRAIN_LEARNING_RATE:-0.0001}"
PRETRAIN_PATIENCE="${PRETRAIN_PATIENCE:-3}"
PRETRAIN_LAMBDA_CE="${PRETRAIN_LAMBDA_CE:-0.02}"
PRETRAIN_LAMBDA_SCENE_CE="${PRETRAIN_LAMBDA_SCENE_CE:-0.02}"
PRETRAIN_LAMBDA_EVENT_BCE="${PRETRAIN_LAMBDA_EVENT_BCE:-0.02}"
FINETUNE_EPOCHS="${FINETUNE_EPOCHS:-5}"
FINETUNE_LEARNING_RATE="${FINETUNE_LEARNING_RATE:-0.000001}"
NEW_MODULE_LEARNING_RATE="${NEW_MODULE_LEARNING_RATE:-0.000005}"
PROMPT_ROUTER="${PROMPT_ROUTER:-compositional_wiki}"
if [[ "${PROMPT_ROUTER}" == "scene_wiki" ]]; then
    REGIME_LABEL_METHOD="scene_wiki"
else
    REGIME_LABEL_METHOD="${REGIME_LABEL_METHOD:-trend_quantile}"
fi
if [[ "${PROMPT_ROUTER}" == "compositional_wiki" ]]; then
    SCENE_WIKI_CONFIG="${SCENE_WIKI_CONFIG:-configs/wind_event_factor_wiki.json}"
    SCENE_WIKI_EMBEDDINGS="${SCENE_WIKI_EMBEDDINGS:-outputs/wiki/wind_event_factor_wiki_qwen.npz}"
elif [[ "${PROMPT_ROUTER}" == "hybrid_wiki" ]]; then
    SCENE_WIKI_CONFIG="${SCENE_WIKI_CONFIG:-configs/wind_exception_wiki.json}"
    SCENE_WIKI_EMBEDDINGS="${SCENE_WIKI_EMBEDDINGS:-outputs/wiki/wind_exception_wiki_qwen.npz}"
else
    SCENE_WIKI_CONFIG="${SCENE_WIKI_CONFIG:-configs/wind_regime_wiki.json}"
    SCENE_WIKI_EMBEDDINGS="${SCENE_WIKI_EMBEDDINGS:-outputs/wiki/wind_regime_wiki_qwen.npz}"
fi
SCENE_WIKI_TOP_K="${SCENE_WIKI_TOP_K:-2}"
SCENE_WIKI_TEMPERATURE="${SCENE_WIKI_TEMPERATURE:-0.2}"
SCENE_WIKI_RULE_WEIGHT="${SCENE_WIKI_RULE_WEIGHT:-2.0}"
SCENE_WIKI_PROMPT_GATE_INIT="${SCENE_WIKI_PROMPT_GATE_INIT:--2.2}"
SCENE_WIKI_ACTIVATION_THRESHOLD="${SCENE_WIKI_ACTIVATION_THRESHOLD:-0.55}"
SCENE_WIKI_CONFIDENCE_POWER="${SCENE_WIKI_CONFIDENCE_POWER:-1.0}"
UTILITY_WIKI="${UTILITY_WIKI:-0}"
UTILITY_LOSS_WEIGHT="${UTILITY_LOSS_WEIGHT:-0.1}"
UTILITY_GATE_TEMPERATURE="${UTILITY_GATE_TEMPERATURE:-0.25}"
UTILITY_MIN_GAIN="${UTILITY_MIN_GAIN:-0.02}"
UTILITY_TARGET_EPS="${UTILITY_TARGET_EPS:-0.05}"
WIKI_LLM_PATH="${WIKI_LLM_PATH:-Qwen/Qwen2.5-0.5B}"
WIKI_BUILD_DEVICE="${WIKI_BUILD_DEVICE:-auto}"
REGIME_CALIBRATION_QUANTILE="${REGIME_CALIBRATION_QUANTILE:-0.3333333333}"
REGIME_CALIBRATION_SAMPLES="${REGIME_CALIBRATION_SAMPLES:-50000}"
REGIME_MIN_CLASS_FRACTION="${REGIME_MIN_CLASS_FRACTION:-0.05}"
FINETUNE_PATIENCE="${FINETUNE_PATIENCE:-2}"
FINETUNE_PCT_START="${FINETUNE_PCT_START:-0.20}"
LOSS="${LOSS:-MIXED}"
MIX_MSE_WEIGHT="${MIX_MSE_WEIGHT:-0.2}"
EARLY_STOP_METRIC="${EARLY_STOP_METRIC:-original_mae}"
RATED_POWER="${RATED_POWER:-1500}"
GPU="${GPU:-0}"
MODEL="PromptTimeDART"
CHANNEL_PRIOR=1
OP_CONTEXT=1
REVIN_KEEP_WIND=1
PIPELINE_ID="${PIPELINE_ID:-full_h${PRED_LEN}_${SPLIT}_f${FOLD}_s${SEED}_$(date +%Y%m%d_%H%M%S)}"
PRETRAIN_RUN_ID="${PRETRAIN_RUN_ID:-${PIPELINE_ID}_pretrain}"
LOG_PARAMETERS="h${PRED_LEN}_${SPLIT}_f${FOLD}of${N_FOLDS}_s${SEED}_pt${PRETRAIN_PRED_LEN}_pte${PRETRAIN_EPOCHS}_ptlr${PRETRAIN_LEARNING_RATE}_lce${PRETRAIN_LAMBDA_CE}_lebce${PRETRAIN_LAMBDA_EVENT_BCE}_fte${FINETUNE_EPOCHS}_blr${FINETUNE_LEARNING_RATE}_nlr${NEW_MODULE_LEARNING_RATE}_mix${MIX_MSE_WEIGHT}_${PROMPT_ROUTER}_uw${UTILITY_WIKI}_ulw${UTILITY_LOSS_WEIGHT}_ugt${UTILITY_GATE_TEMPERATURE}_umg${UTILITY_MIN_GAIN}_reg${REGIME_LABEL_METHOD}_rq${REGIME_CALIBRATION_QUANTILE}"
sdwpf_log_init "pipeline" "${LOG_PARAMETERS}" "pipeline.log" "${PIPELINE_ID}"
sdwpf_log_install_exit_trap
LOG_DIR="${SDWPF_LOG_DIR}"

mkdir -p "${LOG_DIR}"
sdwpf_log_capture
echo "[PIPELINE] Log directory: ${LOG_DIR}"
{
    echo "PIPELINE_ID=${PIPELINE_ID}"
    echo "PRETRAIN_RUN_ID=${PRETRAIN_RUN_ID}"
    echo "SEED=${SEED}"
    echo "FOLD=${FOLD}"
    echo "N_FOLDS=${N_FOLDS}"
    echo "SPLIT=${SPLIT}"
    echo "PRED_LEN=${PRED_LEN}"
    echo "PRETRAIN_PRED_LEN=${PRETRAIN_PRED_LEN}"
    echo "PRETRAIN_EPOCHS=${PRETRAIN_EPOCHS}"
    echo "PRETRAIN_LEARNING_RATE=${PRETRAIN_LEARNING_RATE}"
    echo "PRETRAIN_PATIENCE=${PRETRAIN_PATIENCE}"
    echo "PRETRAIN_LAMBDA_CE=${PRETRAIN_LAMBDA_CE}"
    echo "PRETRAIN_LAMBDA_SCENE_CE=${PRETRAIN_LAMBDA_SCENE_CE}"
    echo "PRETRAIN_LAMBDA_EVENT_BCE=${PRETRAIN_LAMBDA_EVENT_BCE}"
    echo "FINETUNE_EPOCHS=${FINETUNE_EPOCHS}"
    echo "FINETUNE_LEARNING_RATE=${FINETUNE_LEARNING_RATE}"
    echo "NEW_MODULE_LEARNING_RATE=${NEW_MODULE_LEARNING_RATE}"
    echo "PROMPT_ROUTER=${PROMPT_ROUTER}"
    echo "SCENE_WIKI_CONFIG=${SCENE_WIKI_CONFIG}"
    echo "SCENE_WIKI_EMBEDDINGS=${SCENE_WIKI_EMBEDDINGS}"
    echo "SCENE_WIKI_TOP_K=${SCENE_WIKI_TOP_K}"
    echo "SCENE_WIKI_TEMPERATURE=${SCENE_WIKI_TEMPERATURE}"
    echo "SCENE_WIKI_RULE_WEIGHT=${SCENE_WIKI_RULE_WEIGHT}"
    echo "SCENE_WIKI_PROMPT_GATE_INIT=${SCENE_WIKI_PROMPT_GATE_INIT}"
    echo "SCENE_WIKI_ACTIVATION_THRESHOLD=${SCENE_WIKI_ACTIVATION_THRESHOLD}"
    echo "SCENE_WIKI_CONFIDENCE_POWER=${SCENE_WIKI_CONFIDENCE_POWER}"
    echo "UTILITY_WIKI=${UTILITY_WIKI}"
    echo "UTILITY_LOSS_WEIGHT=${UTILITY_LOSS_WEIGHT}"
    echo "UTILITY_GATE_TEMPERATURE=${UTILITY_GATE_TEMPERATURE}"
    echo "UTILITY_MIN_GAIN=${UTILITY_MIN_GAIN}"
    echo "UTILITY_TARGET_EPS=${UTILITY_TARGET_EPS}"
    echo "WIKI_LLM_PATH=${WIKI_LLM_PATH}"
    echo "REGIME_LABEL_METHOD=${REGIME_LABEL_METHOD}"
    echo "REGIME_CALIBRATION_QUANTILE=${REGIME_CALIBRATION_QUANTILE}"
    echo "REGIME_CALIBRATION_SAMPLES=${REGIME_CALIBRATION_SAMPLES}"
    echo "REGIME_MIN_CLASS_FRACTION=${REGIME_MIN_CLASS_FRACTION}"
    echo "FINETUNE_PATIENCE=${FINETUNE_PATIENCE}"
    echo "FINETUNE_PCT_START=${FINETUNE_PCT_START}"
    echo "LOSS=${LOSS}"
    echo "MIX_MSE_WEIGHT=${MIX_MSE_WEIGHT}"
    echo "EARLY_STOP_METRIC=${EARLY_STOP_METRIC}"
    echo "RATED_POWER=${RATED_POWER}"
    echo "MODEL=${MODEL}"
    echo "CHANNEL_PRIOR=${CHANNEL_PRIOR}"
    echo "OP_CONTEXT=${OP_CONTEXT}"
    echo "REVIN_KEEP_WIND=${REVIN_KEEP_WIND}"
    echo "LOG_DIR=${LOG_DIR}"
    echo "STARTED_AT=$(date --iso-8601=seconds)"
} > "${LOG_DIR}/pipeline.env"

echo "[PIPELINE] Stage 1/2: fold-matched pretraining"
SEED="${SEED}" \
FOLD="${FOLD}" \
N_FOLDS="${N_FOLDS}" \
SPLIT="${SPLIT}" \
PRED_LEN="${PRETRAIN_PRED_LEN}" \
EVAL_STRIDE=6 \
TRAIN_EPOCHS="${PRETRAIN_EPOCHS}" \
LEARNING_RATE="${PRETRAIN_LEARNING_RATE}" \
PATIENCE="${PRETRAIN_PATIENCE}" \
LAMBDA_CE="${PRETRAIN_LAMBDA_CE}" \
LAMBDA_SCENE_CE="${PRETRAIN_LAMBDA_SCENE_CE}" \
LAMBDA_EVENT_BCE="${PRETRAIN_LAMBDA_EVENT_BCE}" \
PROMPT_ROUTER="${PROMPT_ROUTER}" \
SCENE_WIKI_CONFIG="${SCENE_WIKI_CONFIG}" \
SCENE_WIKI_EMBEDDINGS="${SCENE_WIKI_EMBEDDINGS}" \
SCENE_WIKI_TOP_K="${SCENE_WIKI_TOP_K}" \
SCENE_WIKI_TEMPERATURE="${SCENE_WIKI_TEMPERATURE}" \
SCENE_WIKI_RULE_WEIGHT="${SCENE_WIKI_RULE_WEIGHT}" \
SCENE_WIKI_PROMPT_GATE_INIT="${SCENE_WIKI_PROMPT_GATE_INIT}" \
SCENE_WIKI_ACTIVATION_THRESHOLD="${SCENE_WIKI_ACTIVATION_THRESHOLD}" \
SCENE_WIKI_CONFIDENCE_POWER="${SCENE_WIKI_CONFIDENCE_POWER}" \
WIKI_LLM_PATH="${WIKI_LLM_PATH}" \
WIKI_BUILD_DEVICE="${WIKI_BUILD_DEVICE}" \
REGIME_LABEL_METHOD="${REGIME_LABEL_METHOD}" \
REGIME_CALIBRATION_QUANTILE="${REGIME_CALIBRATION_QUANTILE}" \
REGIME_CALIBRATION_SAMPLES="${REGIME_CALIBRATION_SAMPLES}" \
REGIME_MIN_CLASS_FRACTION="${REGIME_MIN_CLASS_FRACTION}" \
RATED_POWER="${RATED_POWER}" \
GPU="${GPU}" \
PRETRAIN_RUN_ID="${PRETRAIN_RUN_ID}" \
RUN_ID="${PIPELINE_ID}_pretrain" \
SDWPF_LOG_DIR="${LOG_DIR}" \
SDWPF_LOG_FILE="${LOG_DIR}/pretrain.log" \
bash scripts/pretrain/SDWPF.sh

echo "[PIPELINE] Stage 2/2: supervised fine-tuning with the matched checkpoint"
SEED="${SEED}" \
FOLD="${FOLD}" \
N_FOLDS="${N_FOLDS}" \
SPLIT="${SPLIT}" \
PRED_LEN="${PRED_LEN}" \
EVAL_STRIDE="${PRED_LEN}" \
PRETRAIN_RUN_ID="${PRETRAIN_RUN_ID}" \
ALLOW_RANDOM=0 \
PROMPT_ROUTER="${PROMPT_ROUTER}" \
SCENE_WIKI_CONFIG="${SCENE_WIKI_CONFIG}" \
SCENE_WIKI_EMBEDDINGS="${SCENE_WIKI_EMBEDDINGS}" \
SCENE_WIKI_TOP_K="${SCENE_WIKI_TOP_K}" \
SCENE_WIKI_TEMPERATURE="${SCENE_WIKI_TEMPERATURE}" \
SCENE_WIKI_RULE_WEIGHT="${SCENE_WIKI_RULE_WEIGHT}" \
SCENE_WIKI_PROMPT_GATE_INIT="${SCENE_WIKI_PROMPT_GATE_INIT}" \
SCENE_WIKI_ACTIVATION_THRESHOLD="${SCENE_WIKI_ACTIVATION_THRESHOLD}" \
SCENE_WIKI_CONFIDENCE_POWER="${SCENE_WIKI_CONFIDENCE_POWER}" \
UTILITY_WIKI="${UTILITY_WIKI}" \
UTILITY_LOSS_WEIGHT="${UTILITY_LOSS_WEIGHT}" \
UTILITY_GATE_TEMPERATURE="${UTILITY_GATE_TEMPERATURE}" \
UTILITY_MIN_GAIN="${UTILITY_MIN_GAIN}" \
UTILITY_TARGET_EPS="${UTILITY_TARGET_EPS}" \
WIKI_LLM_PATH="${WIKI_LLM_PATH}" \
WIKI_BUILD_DEVICE="${WIKI_BUILD_DEVICE}" \
REGIME_LABEL_METHOD="${REGIME_LABEL_METHOD}" \
REGIME_CALIBRATION_QUANTILE="${REGIME_CALIBRATION_QUANTILE}" \
TRAIN_EPOCHS="${FINETUNE_EPOCHS}" \
LEARNING_RATE="${FINETUNE_LEARNING_RATE}" \
NEW_MODULE_LEARNING_RATE="${NEW_MODULE_LEARNING_RATE}" \
PATIENCE="${FINETUNE_PATIENCE}" \
PCT_START="${FINETUNE_PCT_START}" \
LOSS="${LOSS}" \
MIX_MSE_WEIGHT="${MIX_MSE_WEIGHT}" \
EARLY_STOP_METRIC="${EARLY_STOP_METRIC}" \
RATED_POWER="${RATED_POWER}" \
GPU="${GPU}" \
MODEL="${MODEL}" \
CHANNEL_PRIOR="${CHANNEL_PRIOR}" \
OP_CONTEXT="${OP_CONTEXT}" \
REVIN_KEEP_WIND="${REVIN_KEEP_WIND}" \
RUN_ID="${PIPELINE_ID}_finetune" \
SDWPF_LOG_DIR="${LOG_DIR}" \
SDWPF_LOG_FILE="${LOG_DIR}/finetune.log" \
bash scripts/finetune/SDWPF_ablation_prompt.sh

CHECKPOINT="$(
    grep -F '[AUDIT] FINETUNE_CHECKPOINT=' "${LOG_DIR}/finetune.log" \
        | tail -n 1 \
        | sed 's/^.*FINETUNE_CHECKPOINT=//' \
        || true
)"
if [[ -z "${CHECKPOINT}" ]]; then
    echo "Fine-tuning completed but no checkpoint marker was found." >&2
    exit 3
fi

{
    echo "FINETUNE_CHECKPOINT=${CHECKPOINT}"
    echo "COMPLETED_AT=$(date --iso-8601=seconds)"
} >> "${LOG_DIR}/pipeline.env"

{
    echo "PIPELINE_ID=${PIPELINE_ID}"
    echo "FOLD=${FOLD} SEED=${SEED} SPLIT=${SPLIT} PRED_LEN=${PRED_LEN}"
    grep -E '^Epoch:|^Pretrain early stopping' "${LOG_DIR}/pretrain.log" || true
    grep -E '^Transferred |^Optimizer groups:|^Epoch:|^Early stopping|^\[AUDIT\] FINETUNE_CHECKPOINT=|^\[INFO\] Test evaluation' \
        "${LOG_DIR}/finetune.log" || true
} > "${LOG_DIR}/summary.txt"

echo "[PIPELINE] Training complete; test split has not been read."
echo "[PIPELINE] Logs: ${LOG_DIR}"
echo "[PIPELINE] Summary: ${LOG_DIR}/summary.txt"
echo "[PIPELINE] FINETUNE_CHECKPOINT=${CHECKPOINT}"
if [[ "${SPLIT}" == "rolling_holdout" ]]; then
    echo "[PIPELINE] CV mode: the shared final holdout remains sealed."
    echo "[PIPELINE] Do not test this fold while selecting hyperparameters."
elif [[ "${SPLIT}" == "time_ratio" ]]; then
    echo "[PIPELINE] Final test (run only after model selection):"
    echo "CONFIRM_FINAL_EVAL=1 MODEL=${MODEL} PROMPT_ROUTER=${PROMPT_ROUTER} UTILITY_WIKI=${UTILITY_WIKI} UTILITY_GATE_TEMPERATURE=${UTILITY_GATE_TEMPERATURE} UTILITY_MIN_GAIN=${UTILITY_MIN_GAIN} SCENE_WIKI_CONFIG='${SCENE_WIKI_CONFIG}' SCENE_WIKI_EMBEDDINGS='${SCENE_WIKI_EMBEDDINGS}' SCENE_WIKI_TOP_K=${SCENE_WIKI_TOP_K} SCENE_WIKI_TEMPERATURE=${SCENE_WIKI_TEMPERATURE} SCENE_WIKI_RULE_WEIGHT=${SCENE_WIKI_RULE_WEIGHT} SCENE_WIKI_PROMPT_GATE_INIT=${SCENE_WIKI_PROMPT_GATE_INIT} SCENE_WIKI_ACTIVATION_THRESHOLD=${SCENE_WIKI_ACTIVATION_THRESHOLD} SCENE_WIKI_CONFIDENCE_POWER=${SCENE_WIKI_CONFIDENCE_POWER} SEED=${SEED} FOLD=${FOLD} N_FOLDS=${N_FOLDS} SPLIT=${SPLIT} PRED_LEN=${PRED_LEN} RATED_POWER=${RATED_POWER} GPU=${GPU} FINETUNE_CHECKPOINT='${CHECKPOINT}' bash scripts/eval/SDWPF_logged_final_eval.sh"
else
    echo "[PIPELINE] SPLIT=${SPLIT} is exploratory; no final-test command is valid for this split."
fi
